base_model: output/sft
load_in_4bit: true
train_dataset: data/dpo_data.jsonl
output_dir: output/dpo
per_device_train_batch_size: 1
learning_rate: 1e-5
num_train_epochs: 1
lora_r: 8
lora_alpha: 16
gradient_checkpointing: true
